#include <iostream>
#include "exception.hpp"

int main()
{

	return EXIT_SUCCESS;
}